### Import Necessary Libraries

In [1]:
import numpy as np
import pandas as pd
import plotly.express as px

### Load Data

In [6]:
df = pd.read_csv('../06 EDA fifa project/fifa_eda.csv')
df.head()

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0

# Data Understanding

### 1- Data Info

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18207 entries, 0 to 18206
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        18207 non-null  int64
 1   Name                      18207 non-null  object
 2   Age                       18207 non-null  int64
 3   Nationality               18207 non-null  object
 4   Overall                   18207 non-null  int64
 5   Potential                 18207 non-null  int64
 6   Club                      17966 non-null  object
 7   Value                     17955 non-null  float64
 8   Wage                      18207 non-null  float64
 9   Preferred Foot            18207 non-null  object
 10  International Reputation  18159 non-null  float64
 11  Skill Moves               18159 non-null  float64
 12  Position                  18207 non-null  object
 13  Joined                    18207 non-null  int64
 14  Contract Valid Until      17918 non-null  object
 15  Height                    18207 non-null  float64
 16  Weight                    18207 non-null  float64
 17  Release Clause            18207 non-null  float64
dtypes: float64(7), int64(5), object(6)
memory usage: 2.5+ MB

### 2- Numerical Data Summary Statistics

In [10]:
df.describe().round(1)

,ID,Age,Overall,Potential,Value,Wage,International Reputation,Skill Moves,Joined,Height,Weight,Release Clause
count,18207.0,18207.0,18207.0,18207.0,17955.0,18207.0,18159.0,18159.0,18207.0,18207.0,18207.0,18207.0
mean,214298.3,25.1,66.2,71.3,2444.5,9.7,1.1,2.4,2016.4,5.9,166.0,4585.1
std,29965.2,4.7,6.9,6.1,5626.7,22.0,0.4,0.8,2.0,0.2,15.6,10630.4
min,16.0,16.0,46.0,48.0,10.0,0.0,1.0,1.0,1991.0,5.1,110.0,13.0
25%,200315.5,21.0,62.0,67.0,325.0,1.0,1.0,2.0,2016.0,5.8,154.0,570.0
50%,221759.0,25.0,66.0,71.0,700.0,3.0,1.0,2.0,2017.0,5.9,165.0,1300.0
75%,236529.5,28.0,71.0,75.0,2100.0,9.0,1.0,3.0,2018.0,6.1,176.0,4585.1
max,246620.0,45.0,94.0,95.0,118500.0,565.0,5.0,5.0,2018.0,6.8,243.0,228100.0

### 3- Categorical Data Summary Statistics

In [11]:
df.describe(include= 'O')

,Name,Nationality,Club,Preferred Foot,Position,Contract Valid Until
count,18207,18207,17966,18207,18207,17918
unique,17194,164,651,2,27,35
top,J. Rodríguez,England,FC Barcelona,Right,ST,2019-01-01
freq,11,1662,33,13996,2154,4870

### 4- Check Missing Values

In [12]:
# By Count
df.isna().sum()

ID                            0
Name                          0
Age                           0
Nationality                   0
Overall                       0
Potential                     0
Club                        241
Value                       252
Wage                          0
Preferred Foot                0
International Reputation     48
Skill Moves                  48
Position                      0
Joined                        0
Contract Valid Until        289
Height                        0
Weight                        0
Release Clause                0
dtype: int64

In [13]:
# By Percentage 
(df.isna().sum() / df.shape[0]) * 100

ID                          0.000000
Name                        0.000000
Age                         0.000000
Nationality                 0.000000
Overall                     0.000000
Potential                   0.000000
Club                        1.323667
Value                       1.384083
Wage                        0.000000
Preferred Foot              0.000000
International Reputation    0.263635
Skill Moves                 0.263635
Position                    0.000000
Joined                      0.000000
Contract Valid Until        1.587302
Height                      0.000000
Weight                      0.000000
Release Clause              0.000000
dtype: float64

In [14]:
df.isna().mean() *100

ID                          0.000000
Name                        0.000000
Age                         0.000000
Nationality                 0.000000
Overall                     0.000000
Potential                   0.000000
Club                        1.323667
Value                       1.384083
Wage                        0.000000
Preferred Foot              0.000000
International Reputation    0.263635
Skill Moves                 0.263635
Position                    0.000000
Joined                      0.000000
Contract Valid Until        1.587302
Height                      0.000000
Weight                      0.000000
Release Clause              0.000000
dtype: float64

### 5- Check Duplicates

In [15]:
df.duplicated().sum()

np.int64(0)

# Data Cleaning

In [16]:
df.columns

Index(['ID', 'Name', 'Age', 'Nationality', 'Overall', 'Potential', 'Club',
       'Value', 'Wage', 'Preferred Foot', 'International Reputation',
       'Skill Moves', 'Position', 'Joined', 'Contract Valid Until', 'Height',
       'Weight', 'Release Clause'],
      dtype='object')

In [17]:
# Make columns lowercase and replace space with underscore
df.columns = df.columns.str.lower().str.replace(' ', '_')
df.columns

Index(['id', 'name', 'age', 'nationality', 'overall', 'potential', 'club',
       'value', 'wage', 'preferred_foot', 'international_reputation',
       'skill_moves', 'position', 'joined', 'contract_valid_until', 'height',
       'weight', 'release_clause'],
      dtype='object')

In [23]:
# Update datatype of contract column
df.contract_valid_until = pd.to_datetime(df.contract_valid_until)
df.contract_valid_until

0       2021-01-01
1       2022-01-01
2       2022-01-01
3       2020-01-01
4       2023-01-01
           ...
18202   2019-01-01
18203   2020-01-01
18204   2021-01-01
18205   2019-01-01
18206   2019-01-01
Name: contract_valid_until, Length: 18207, dtype: datetime64[ns]

- Check inconsistent minimum value in wage column which is equal to zero

In [27]:
df[df.wage < 1]

,id,name,age,nationality,overall,potential,club,value,wage,preferred_foot,international_reputation,skill_moves,position,joined,contract_valid_until,height,weight,release_clause
452,207439,L. Paredes,24,Argentina,80,85,NaN,NaN,0.0,Right,2.0,4.0,CM,2016,NaT,5.916667,165.0,4585.060806
538,156713,A. Granqvist,33,Sweden,80,80,NaN,NaN,0.0,Right,2.0,2.0,LCB,2016,NaT,6.333333,185.0,4585.060806
568,229909,A. Lunev,26,Russia,79,81,NaN,NaN,0.0,Right,1.0,1.0,GK,2016,NaT,6.166667,176.0,4585.060806
677,187347,I. Smolnikov,29,Russia,79,79,NaN,NaN,0.0,Right,2.0,3.0,RB,2016,NaT,5.833333,154.0,4585.060806
874,187607,A. Dzyuba,29,Russia,78,78,NaN,NaN,0.0,Right,2.0,3.0,ST,2016,NaT,6.416667,201.0,4585.060806
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17197,245164,V. Kaith,21,India,55,64,NaN,NaN,0.0,Right,1.0,1.0,GK,2016,NaT,6.166667,176.0,4585.060806
17215,243131,K. Taimi,26,Finland,55,57,NaN,NaN,0.0,Right,1.0,2.0,RB,2016,NaT,6.333333,187.0,4585.060806
17339,233526,S. Passi,23,India,54,63,NaN,NaN,0.0,Right,1.0,2.0,RM,2016,NaT,5.750000,143.0,4585.060806
17436,236452,D. Lalhlimpuia,20,India,54,67,NaN,NaN,0.0,Right,1.0,2.0,GK,2016,NaT,6.000000,168.0,4585.060806
17539,234508,C. Singh,21,India,53,62,NaN,NaN,0.0,Right,1.0,2.0,LB,2016,NaT,6.250000,174.0,4585.060806

In [26]:
df[df.wage < 1].count()

id                          241
name                        241
age                         241
nationality                 241
overall                     241
potential                   241
club                          0
value                         0
wage                        241
preferred_foot              241
international_reputation    241
skill_moves                 241
position                    241
joined                      241
contract_valid_until          0
height                      241
weight                      241
release_clause              241
dtype: int64

In [28]:
# Detect all rows that need to be dropped
drop_indices = df[df.wage < 1].index
drop_indices

Index([  452,   538,   568,   677,   874,   953,   997,  1008,  1120,  1271,
       ...
       16903, 16947, 16976, 17008, 17129, 17197, 17215, 17339, 17436, 17539],
      dtype='int64', length=241)

In [29]:
len(drop_indices)

241

In [30]:
# Drop all rows where wage equal 0
df.drop(drop_indices, inplace= True)

In [32]:
# this df is unsorted becouse of the drop
df

,id,name,age,nationality,overall,potential,club,value,wage,preferred_foot,international_reputation,skill_moves,position,joined,contract_valid_until,height,weight,release_clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [33]:
# Reset the index always after removing any rows from the data
df.reset_index(drop= True, inplace= True)

In [34]:
df

,id,name,age,nationality,overall,potential,club,value,wage,preferred_foot,international_reputation,skill_moves,position,joined,contract_valid_until,height,weight,release_clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17961,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
17962,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
17963,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
17964,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
17965,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

### Handling Missing Values

In [36]:
round(df.isna().mean() * 100 , 3)

id                          0.000
name                        0.000
age                         0.000
nationality                 0.000
overall                     0.000
potential                   0.000
club                        0.000
value                       0.061
wage                        0.000
preferred_foot              0.000
international_reputation    0.267
skill_moves                 0.267
position                    0.000
joined                      0.000
contract_valid_until        0.267
height                      0.000
weight                      0.000
release_clause              0.000
dtype: float64

In [37]:
round((df.isna().sum() / df.shape[0]) * 100, 3)

id                          0.000
name                        0.000
age                         0.000
nationality                 0.000
overall                     0.000
potential                   0.000
club                        0.000
value                       0.061
wage                        0.000
preferred_foot              0.000
international_reputation    0.267
skill_moves                 0.267
position                    0.000
joined                      0.000
contract_valid_until        0.267
height                      0.000
weight                      0.000
release_clause              0.000
dtype: float64

In [38]:
df.value

0        110500.0
1         77000.0
2        118500.0
3         72000.0
4        102000.0
           ...
17961        60.0
17962        60.0
17963        60.0
17964        60.0
17965        60.0
Name: value, Length: 17966, dtype: float64

In [39]:
# replace all missing values in value column with the median
value_median = df.value.median()
value_median

np.float64(700.0)

In [41]:
df.value = df.value.fillna(value_median)
df.value

0        110500.0
1         77000.0
2        118500.0
3         72000.0
4        102000.0
           ...
17961        60.0
17962        60.0
17963        60.0
17964        60.0
17965        60.0
Name: value, Length: 17966, dtype: float64

In [42]:
round((df.isna().sum() / df.shape[0]) * 100, 3)

id                          0.000
name                        0.000
age                         0.000
nationality                 0.000
overall                     0.000
potential                   0.000
club                        0.000
value                       0.000
wage                        0.000
preferred_foot              0.000
international_reputation    0.267
skill_moves                 0.267
position                    0.000
joined                      0.000
contract_valid_until        0.267
height                      0.000
weight                      0.000
release_clause              0.000
dtype: float64

In [45]:
df[ (df.international_reputation.isna()) & (df.skill_moves.isna()) & (df.contract_valid_until.isna()) ].head()

,id,name,age,nationality,overall,potential,club,value,wage,preferred_foot,international_reputation,skill_moves,position,joined,contract_valid_until,height,weight,release_clause
13041,177971,J. McNulty,33,Scotland,62,62,Rochdale,120.0,1.0,Right,NaN,NaN,LB,2016,NaT,5.946771,165.979129,4585.060806
13042,195380,J. Barrera,29,Nicaragua,62,62,Boyacá Chicó FC,300.0,1.0,Right,NaN,NaN,LB,2016,NaT,5.946771,165.979129,4585.060806
13043,139317,J. Stead,35,England,62,62,Notts County,140.0,3.0,Right,NaN,NaN,LB,2016,NaT,5.946771,165.979129,4585.060806
13044,240437,A. Semprini,20,Italy,62,72,Brescia,425.0,1.0,Right,NaN,NaN,LB,2016,NaT,5.946771,165.979129,4585.060806
13045,209462,R. Bingham,24,England,62,66,Hamilton Academical FC,400.0,1.0,Right,NaN,NaN,LB,2016,NaT,5.946771,165.979129,4585.060806

In [46]:
# Drop all Missing Values in the dataframe
df.dropna(inplace= True, ignore_index= True)

In [47]:
df

,id,name,age,nationality,overall,potential,club,value,wage,preferred_foot,international_reputation,skill_moves,position,joined,contract_valid_until,height,weight,release_clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17913,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
17914,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
17915,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
17916,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
17917,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [84]:
# In case we need to specify columns to drop missing values from
# df.dropna(subset= ['skill_moves', 'international_reputation', 'contract_valid_until'])

In [48]:
round((df.isna().sum() / df.shape[0]) * 100, 3)

id                          0.0
name                        0.0
age                         0.0
nationality                 0.0
overall                     0.0
potential                   0.0
club                        0.0
value                       0.0
wage                        0.0
preferred_foot              0.0
international_reputation    0.0
skill_moves                 0.0
position                    0.0
joined                      0.0
contract_valid_until        0.0
height                      0.0
weight                      0.0
release_clause              0.0
dtype: float64

### In depth check for categorical columns

In [50]:
cat_cols = df.select_dtypes(include= 'object').columns
cat_cols

Index(['name', 'nationality', 'club', 'preferred_foot', 'position'], dtype='object')

In [51]:
for col in cat_cols:
    print(col)
    print(df[col].nunique())
    print(df[col].unique(), '\n')

name
16924
['L. Messi' 'Cristiano Ronaldo' 'Neymar Jr' ... 'B. Worman'
 'D. Walker-Rice' 'G. Nugent']

nationality
163
['Argentina' 'Portugal' 'Brazil' 'Spain' 'Belgium' 'Croatia' 'Uruguay'
 'Slovenia' 'Poland' 'Germany' 'France' 'England' 'Italy' 'Egypt'
 'Colombia' 'Denmark' 'Gabon' 'Wales' 'Senegal' 'Costa Rica' 'Slovakia'
 'Netherlands' 'Bosnia Herzegovina' 'Morocco' 'Serbia' 'Algeria' 'Austria'
 'Greece' 'Chile' 'Sweden' 'Korea Republic' 'Finland' 'Guinea'
 'Montenegro' 'Armenia' 'Switzerland' 'Norway' 'Czech Republic' 'Scotland'
 'Ghana' 'Central African Rep.' 'DR Congo' 'Ivory Coast' 'Russia'
 'Ukraine' 'Iceland' 'Mexico' 'Jamaica' 'Albania' 'Venezuela' 'Japan'
 'Turkey' 'Ecuador' 'Paraguay' 'Mali' 'Nigeria' 'Cameroon'
 'Dominican Republic' 'Israel' 'Kenya' 'Hungary' 'Republic of Ireland'
 'Romania' 'United States' 'Cape Verde' 'Australia' 'Peru' 'Togo' 'Syria'
 'Zimbabwe' 'Angola' 'Burkina Faso' 'Iran' 'Estonia' 'Tunisia'
 'Equatorial Guinea' 'New Zealand' 'FYR Macedonia' 'United Arab Emirates'
 'China PR' 'Guinea Bissau' 'Bulgaria' 'Kosovo' 'South Africa'
 'Madagascar' 'Georgia' 'Tanzania' 'Gambia' 'Cuba' 'Belarus' 'Uzbekistan'
 'Benin' 'Congo' 'Mozambique' 'Honduras' 'Canada' 'Northern Ireland'
 'Cyprus' 'Saudi Arabia' 'Curacao' 'Moldova' 'Bolivia' 'Trinidad & Tobago'
 'Sierra Leone' 'Zambia' 'Chad' 'Philippines' 'Haiti' 'Comoros' 'Libya'
 'Panama' 'São Tomé & Príncipe' 'Eritrea' 'Oman' 'Iraq' 'Burundi' 'Fiji'
 'New Caledonia' 'Lithuania' 'Luxembourg' 'Korea DPR' 'Liechtenstein'
 'St Kitts Nevis' 'Latvia' 'Suriname' 'Uganda' 'El Salvador' 'Bermuda'
 'Kuwait' 'Antigua & Barbuda' 'Thailand' 'Mauritius' 'Guatemala' 'Liberia'
 'Kazakhstan' 'Niger' 'Mauritania' 'Montserrat' 'Namibia' 'Azerbaijan'
 'Guam' 'Faroe Islands' 'Nicaragua' 'Barbados' 'Lebanon' 'Palestine'
 'Guyana' 'Sudan' 'St Lucia' 'Ethiopia' 'Puerto Rico' 'Grenada' 'Jordan'
 'Rwanda' 'Qatar' 'Afghanistan' 'Hong Kong' 'Andorra' 'Malta' 'Belize'
 'South Sudan' 'Indonesia' 'Botswana']

club
651
['FC Barcelona' 'Juventus' 'Paris Saint-Germain' 'Manchester United'
 'Manchester City' 'Chelsea' 'Real Madrid' 'Atlético Madrid'
 'FC Bayern München' 'Tottenham Hotspur' 'Liverpool' 'Napoli' 'Arsenal'
 'Milan' 'Inter' 'Lazio' 'Borussia Dortmund' 'Vissel Kobe'
 'Olympique Lyonnais' 'Roma' 'Valencia CF'
 'Guangzhou Evergrande Taobao FC' 'FC Porto' 'FC Schalke 04' 'Beşiktaş JK'
 'LA Galaxy' 'Sporting CP' 'Real Betis' 'Olympique de Marseille'
 'RC Celta' 'Bayer 04 Leverkusen' 'Real Sociedad' 'Villarreal CF'
 'Sevilla FC' 'SL Benfica' 'AS Saint-Étienne' 'AS Monaco' 'Leicester City'
 'Atalanta' 'Grêmio' 'Atlético Mineiro' 'RB Leipzig' 'Ajax'
 'Dalian YiFang FC' 'Everton' 'West Ham United' '1. FC Köln'
 'TSG 1899 Hoffenheim' 'Shanghai SIPG FC' 'OGC Nice' 'Al Nassr'
 'Wolverhampton Wanderers' 'Borussia Mönchengladbach' 'Hertha BSC'
 'SV Werder Bremen' 'Cruzeiro' 'Athletic Club de Bilbao' 'Torino'
 'Medipol Başakşehir FK' 'Beijing Sinobo Guoan FC' 'Crystal Palace'
 'PFC CSKA Moscow' 'VfL Wolfsburg' 'Shakhtar Donetsk' 'Toronto FC'
 'Lokomotiv Moscow' 'Sassuolo' 'New York City FC' 'Fluminense' 'PSV'
 'Levante UD' 'Fulham' 'Watford' 'Atlanta United' 'Montpellier HSC'
 'Galatasaray SK' 'Fenerbahçe SK' 'SD Eibar' 'Los Angeles FC' 'Sampdoria'
 'Al Hilal' 'VfB Stuttgart' 'SC Braga' 'River Plate' 'Deportivo Alavés'
 'Eintracht Frankfurt' 'Girona FC' 'Guangzhou R&F; FC' 'Burnley'
 'Stoke City' 'Southampton' 'Tianjin Quanjian FC' 'Getafe CF'
 'Beijing Renhe FC' 'Montreal Impact' 'Chievo Verona' 'Genoa'
 'Portland Timbers' 'Tigres U.A.N.L.' 'RCD Espanyol'
 'Hebei China Fortune FC' 'Cagliari' 'Chicago Fire' 'DC United'
 'Sagan Tosu' 'Dynamo Kyiv' 'Santos' 'Internacional'
 'América FC (Minas Gerais)' 'Independiente' 'Boca Juniors' 'Cruz Azul'
 '1. FSV Mainz 05' 'Bournemouth' 'Spartak Moscow' 'Racing Club'
 'FC Augsburg' 'Fiorentina' 'FC Nantes' 'Feyenoord' 'Club Brugge KV'
 'Brighton & Hove Albion' 'Al Ahli' 'Jiangsu Suning FC' 'SC Freiburg'
 'PAOK' 'Stade Rennais FC' 'Trabzonspor' 'SPAL' 'Portimonense SC'
 'Olympiacos CFP' 'Club Atlético Huracán' 'Kasimpaşa SK'
 'Newcastle United' 'Frosinone' 'Querétaro' 'KRC Genk' 'Hannover 96'
 'Stade Malherbe Caen' 'Godoy Cruz' 'Toulouse Football Club'
 'RSC Anderlecht' 'Huddersfield Town' 'CD Tondela' 'Seattle Sounders FC'
 'Hamburger SV' 'FC Red Bull Salzburg' 'Rio Ave FC'
 'FC Girondins de Bordeaux' 'Melbourne Victory' 'Parma' 'FC Basel 1893'
 'Al Wehda' 'BSC Young Boys' 'KAA Gent' 'Al Ittihad' 'Standard de Liège'
 'Shanghai Greenland Shenhua FC' 'Colo-Colo' 'Junior FC'
 'West Bromwich Albion' 'RC Strasbourg Alsace' 'Göztepe SK'
 'Deportivo Cali' 'Deportivo Toluca' 'Bologna' 'Nagoya Grampus'
 'Amiens SC' 'Changchun Yatai FC' 'Club Atlético Lanús' 'Botafogo'
 'Club América' 'Udinese' 'Real Valladolid CF' 'CD Leganés'
 'Club Atlético Banfield' 'Celtic' 'Vitória Guimarães' 'FC København'
 'UD Las Palmas' 'Deportivo de La Coruña' 'Universidad Católica'
 'San Lorenzo de Almagro' 'Rayo Vallecano' 'Monterrey' 'Columbus Crew SC'
 'MKE Ankaragücü' 'Guizhou Hengfeng FC' 'Swansea City' 'Tianjin TEDA FC'
 'Chongqing Dangdai Lifan FC SWM Team' 'AEK Athens' 'Al Taawoun'
 'Melbourne City FC' 'En Avant de Guingamp' 'Akhisar Belediyespor'
 'Foggia' 'LOSC Lille' '1. FC Nürnberg' 'Clube Sport Marítimo'
 'Real Sporting de Gijón' 'BB Erzurumspor' 'Shandong Luneng TaiShan FC'
 'Club Atlético Colón' 'Bahia' 'Once Caldas' 'FC Groningen' 'Angers SCO'
 'Paraná' 'Antalyaspor' 'Minnesota United FC' 'Club León' 'Empoli'
 'VVV-Venlo' 'Leeds United' 'Viktoria Plzeň' 'Alanyaspor'
 'Atlético Paranaense' 'Derby County' 'Kawasaki Frontale' 'Cardiff City'
 'Aston Villa' 'Guadalajara' 'Dijon FCO' 'Santos Laguna' 'Málaga CF'
 'Vitória' 'Çaykur Rizespor' 'U.N.A.M.' 'Nottingham Forest'
 'Royal Antwerp FC' 'Club Tijuana' 'Sport Club do Recife' 'Real Salt Lake'
 'AZ Alkmaar' 'SK Slavia Praha' 'Willem II' 'Middlesbrough'
 'Dinamo Zagreb' 'Club Atlas' 'Granada CF' 'Sydney FC'
 'Sporting Kansas City' 'SV Zulte-Waregem' 'Philadelphia Union'
 'Real Oviedo' 'Pachuca' 'Boavista FC' 'Atiker Konyaspor' 'Kaizer Chiefs'
 'GD Chaves' 'Palermo' 'Atlético Nacional' 'Puebla FC' 'Perth Glory'
 'Panathinaikos FC' 'FC Sion' 'Vitória de Setúbal' 'New York Red Bulls'
 'Al Shabab' 'Monarcas Morelia' 'Albacete BP' 'Rangers FC' 'Sparta Praha'
 'Legia Warszawa' 'Urawa Red Diamonds' 'Rosario Central' 'Stade de Reims'
 'ADO Den Haag' 'Chapecoense' 'FC Midtjylland' 'San Jose Earthquakes'
 'Belgrano de Córdoba' 'Brescia' 'Kashima Antlers'
 'CD Everton de Viña del Mar' 'Fortuna Düsseldorf' 'SD Huesca'
 'Preston North End' 'Club Atlético Talleres' 'Benevento' 'Vitesse'
 'Gimnasia y Esgrima La Plata' 'Houston Dynamo' 'Club Necaxa'
 'Norwich City' 'Holstein Kiel' 'Ettifaq FC' 'Kayserispor'
 '1. FC Heidenheim 1846' 'Brentford' 'Yeni Malatyaspor' 'Lobos BUAP'
 'Bursaspor' 'Ceará Sporting Club' 'Sheffield United' 'FC Ingolstadt 04'
 'Estudiantes de La Plata' 'AIK' 'Queens Park Rangers'
 'Suwon Samsung Bluewings' 'Heart of Midlothian' 'Reading' 'FC Dallas'
 'Heracles Almelo' 'Venezia FC' 'CD Lugo' 'Henan Jianye FC'
 'Orlando City SC' 'CA Osasuna' 'NAC Breda' 'Livorno'
 'Universidad de Chile' 'Brøndby IF' 'Aberdeen' 'Defensa y Justicia'
 'Atlético Tucumán' 'Blackburn Rovers' 'SV Darmstadt 98' 'Moreirense FC'
 'Sanfrecce Hiroshima' 'CD Numancia' 'KV Oostende' 'FC Utrecht'
 'Vancouver Whitecaps FC' 'Odense Boldklub' 'SC Heerenveen'
 'Racing Club de Lens' 'Independiente Santa Fe' 'Sporting de Charleroi'
 'Millonarios FC' 'Sheffield Wednesday' 'Perugia' 'Daegu FC'
 'Vélez Sarsfield' 'Grasshopper Club Zürich' 'Sivasspor' 'Nîmes Olympique'
 'Rosenborg BK' 'SK Sturm Graz' 'FC Metz' 'CD Universidad de Concepción'
 'Hellas Verona' 'Brisbane Roar' 'CD Feirense' 'Hull City'
 'Waasland-Beveren' 'Neuchâtel Xamax' 'Real Zaragoza' 'CD Aves' 'Millwall'
 'Unión de Santa Fe' 'KAS Eupen' 'Cádiz CF' 'FC Tokyo' 'CD Tenerife'
 '1. FC Union Berlin' 'Al Fayha' 'AJ Auxerre' 'Patriotas Boyacá FC'
 'Molde FK' 'Bristol City' 'CD Nacional' 'Sporting Lokeren' 'FC St. Pauli'
 'Deportes Iquique' 'Al Qadisiyah' 'Atlético Bucaramanga'
 'Club Atlético Tigre' 'FK Austria Wien' 'Patronato' 'Malmö FF'
 'Kashiwa Reysol' 'US Cremonese' 'VfL Bochum 1848' 'SK Rapid Wien'
 'KSV Cercle Brugge' 'Rionegro Águilas' 'Gimnàstic de Tarragona' 'Lecce'
 'Santa Clara' 'BK Häcken' 'New England Revolution' 'Orlando Pirates'
 'Atlético Huila' 'Western Sydney Wanderers' 'Kalmar FF'
 'Independiente Medellín' 'Fortuna Sittard' 'Lech Poznań' 'Djurgårdens IF'
 'CF Reus Deportiu' 'SK Brann' 'Ulsan Hyundai FC' 'Sint-Truidense VV'
 'Carpi' 'Al Fateh' 'Royal Excel Mouscron' 'AC Ajaccio' 'PEC Zwolle'
 'Sunderland' 'Club Atlético Aldosivi' 'US Salernitana 1919' 'FC Lorient'
 'Argentinos Juniors' 'AD Alcorcón' 'Crotone' 'Excelsior' 'KV Kortrijk'
 'IFK Norrköping' 'Adelaide United' 'FC St. Gallen'
 'Tiburones Rojos de Veracruz' 'CD Palestino' 'Jeju United FC'
 'Deportes Tolima' 'Jeonbuk Hyundai Motors' 'Birmingham City'
 'América de Cali' 'La Equidad' 'Spezia' 'Aalborg BK' 'Le Havre AC'
 'Górnik Zabrze' 'Central Coast Mariners' 'Wigan Athletic'
 'Jagiellonia Białystok' 'Cittadella' 'Hibernian' 'FC Lugano'
 'San Martín de San Juan' 'Strømsgodset IF' 'Júbilo Iwata'
 "Newell's Old Boys" 'Al Faisaly' 'Colorado Rapids' 'IF Elfsborg'
 'SV Sandhausen' 'Al Batin' 'Stade Brestois 29' 'UD Almería'
 'Gyeongnam FC' 'Yokohama F. Marinos' 'Kilmarnock' 'Pescara'
 'Newcastle Jets' 'Córdoba CF' 'RCD Mallorca' 'Hammarby IF' 'Cerezo Osaka'
 'KFC Uerdingen 05' 'Shimizu S-Pulse' 'MSV Duisburg' 'Os Belenenses'
 'DSC Arminia Bielefeld' 'Ipswich Town' 'FC Seoul' 'Lechia Gdańsk'
 'Gamba Osaka' 'CF Rayo Majadahonda' 'LASK Linz' 'Bolton Wanderers'
 'Al Raed' 'Extremadura UD' 'SC Paderborn 07' 'Wellington Phoenix'
 'Unión Española' 'Alianza Petrolera' 'Cracovia' 'Gangwon FC' 'Elche CF'
 'ESTAC Troyes' 'AS Béziers' 'La Berrichonne de Châteauroux'
 'Clermont Foot 63' '1. FC Magdeburg' 'Pohang Steelers' 'Örebro SK'
 'Arka Gdynia' 'SG Dynamo Dresden' 'SpVgg Greuther Fürth' 'CD Huachipato'
 'Wisła Kraków' 'Stabæk Fotball' 'Eintracht Braunschweig'
 'Valenciennes FC' 'FC Thun' 'San Luis de Quillota' ' SSV Jahn Regensburg'
 'Cosenza' 'FC Nordsjælland' 'FC Erzgebirge Aue' 'Jeonnam Dragons'
 'Wolfsberger AC' 'Chamois Niortais Football Club' 'Club Deportes Temuco'
 'AS Nancy Lorraine' 'Red Star FC' 'Al Hazem' 'Pogoń Szczecin'
 'Charlton Athletic' 'Grenoble Foot 38' 'FC Hansa Rostock'
 'San Martin de Tucumán' 'Incheon United FC' 'Śląsk Wrocław' 'GFC Ajaccio'
 '1. FC Kaiserslautern' 'Deportivo Pasto' 'Lincoln City' 'Motherwell'
 'Rotherham United' 'Burton Albion' 'Wisła Płock' 'FC Wacker Innsbruck'
 'Peterborough United' 'Ascoli' 'FC Zürich' 'Fleetwood Town' 'Padova'
 'FC Sochaux-Montbéliard' 'SV Wehen Wiesbaden' 'Unión La Calera'
 'Scunthorpe United' "CD O'Higgins" 'CD Antofagasta' 'Plymouth Argyle'
 'Aarhus GF' 'Lillestrøm SK' 'Karlsruher SC' 'GIF Sundsvall' 'FC Emmen'
 'Barnsley' 'Audax Italiano' 'V-Varen Nagasaki' 'Paris FC'
 'SpVgg Unterhaching' 'Hobro IK' 'De Graafschap'
 'Hokkaido Consadole Sapporo' 'Tromsø IL' 'FC Luzern' 'FK Haugesund'
 'Zagłębie Lubin' 'VfR Aalen' 'Dundalk' 'Oxford United' 'Piast Gliwice'
 'Ohod Club' 'Östersunds FK' 'Vegalta Sendai' 'Crawley Town'
 'FC Admira Wacker Mödling' 'Vålerenga Fotball' 'Dundee FC' 'Portsmouth'
 'Envigado FC' 'Miedź Legnica' 'Odds BK' 'SC Fortuna Köln'
 'US Orléans Loiret Football' 'Sarpsborg 08 FF' 'Jaguares de Córdoba'
 'Bradford City' 'Accrington Stanley' 'St. Johnstone FC' 'Boyacá Chicó FC'
 'Luton Town' 'SV Mattersburg' 'Kristiansund BK' 'Sangju Sangmu FC'
 'Rochdale' 'Walsall' 'Korona Kielce' 'Shonan Bellmare'
 'FC Würzburger Kickers' 'FSV Zwickau' 'St. Mirren' 'AC Horsens'
 'Esbjerg fB' 'HJK Helsinki' 'Southend United' 'Bristol Rovers'
 'Hamilton Academical FC' 'TSV 1860 München' 'Curicó Unido' 'SCR Altach'
 'Ranheim Fotball' 'Stevenage' 'SG Sonnenhof Großaspach' 'Oldham Athletic'
 'Milton Keynes Dons' 'FK Bodø/Glimt' 'SC Preußen Münster'
 'Wycombe Wanderers' 'Vejle Boldklub' 'Bury' 'Randers FC' 'VfL Osnabrück'
 'SønderjyskE' 'IFK Göteborg' 'Mansfield Town' 'Coventry City'
 'Waterford FC' 'Shrewsbury' 'IK Start' 'Gillingham' 'FC Energie Cottbus'
 'FC Carl Zeiss Jena' 'Hallescher FC' 'SV Meppen' 'AFC Wimbledon'
 'Blackpool' 'Doncaster Rovers' 'Sandefjord Fotball'
 'VfL Sportfreunde Lotte' 'Cheltenham Town' 'IK Sirius' 'Vendsyssel FF'
 'Swindon Town' 'Notts County' 'SKN St. Pölten' 'Exeter City'
 'Northampton Town' 'Shamrock Rovers' 'Colchester United' 'Livingston FC'
 'TSV Hartberg' 'Tranmere Rovers' 'Cambridge United' 'Grimsby Town'
 'Port Vale' 'Itagüí Leones FC' 'Forest Green Rovers' 'Dalkurd FF'
 'Zagłębie Sosnowiec' 'Carlisle United' 'Trelleborgs FF'
 "St. Patrick's Athletic" 'Morecambe' 'Cork City' 'IF Brommapojkarna'
 'Crewe Alexandra' 'Yeovil Town' 'Bohemian FC' 'Macclesfield Town'
 'Newport County' 'Sligo Rovers' 'Derry City' 'Limerick FC'
 'Bray Wanderers']

preferred_foot
2
['Left' 'Right']

position
27
['RF' 'ST' 'LW' 'GK' 'RCM' 'LF' 'RS' 'RCB' 'LCM' 'CB' 'LDM' 'CAM' 'CDM'
 'LS' 'LCB' 'RM' 'LAM' 'LM' 'LB' 'RDM' 'RW' 'CM' 'RB' 'RAM' 'CF' 'RWB'
 'LWB']

### In depth check for numerical columns

In [52]:
num_cols = df.select_dtypes(include= ['int', 'float']).columns
num_cols

Index(['id', 'age', 'overall', 'potential', 'value', 'wage',
       'international_reputation', 'skill_moves', 'joined', 'height', 'weight',
       'release_clause'],
      dtype='object')

In [54]:
for col in num_cols:
    print("the column name is: ", col)
    px.histogram(df[col]).show()

the column name is:  id

the column name is:  age

the column name is:  overall

the column name is:  potential

the column name is:  value

the column name is:  wage

the column name is:  international_reputation

the column name is:  skill_moves

the column name is:  joined

the column name is:  height

the column name is:  weight

the column name is:  release_clause

In [55]:
# Convert Height unit from feet to cm
df.height = df.height.apply(lambda x : x * 30.48)
df.height

0        170.18
1        187.96
2        175.26
3        193.04
4        180.34
          ...
17913    175.26
17914    190.50
17915    172.72
17916    177.80
17917    177.80
Name: height, Length: 17918, dtype: float64

In [56]:
# Convert Weight unit from pound to kilogram
df.weight = df.weight.apply(lambda x : x * 0.453592)
df.weight

0        72.121128
1        83.007336
2        68.038800
3        76.203456
4        69.853168
           ...
17913    60.781328
17914    77.110640
17915    67.131616
17916    69.853168
17917    79.832192
Name: weight, Length: 17918, dtype: float64

### **What is the average overall rating for each country ?**

In [57]:
top_10_overall = df.groupby('nationality')['overall'].mean().sort_values(ascending= False).head(10)
top_10_overall

nationality
United Arab Emirates    77.000000
Central African Rep.    73.333333
Israel                  72.142857
Oman                    72.000000
São Tomé & Príncipe     72.000000
Dominican Republic      72.000000
Cape Verde              71.631579
Togo                    71.333333
Portugal                71.327103
Brazil                  71.273939
Name: overall, dtype: float64

In [58]:
type(top_10_overall)

pandas.core.series.Series

In [59]:
top_10_overall.index

Index(['United Arab Emirates', 'Central African Rep.', 'Israel', 'Oman',
       'São Tomé & Príncipe', 'Dominican Republic', 'Cape Verde', 'Togo',
       'Portugal', 'Brazil'],
      dtype='object', name='nationality')

In [60]:
top_10_overall.values

array([77.        , 73.33333333, 72.14285714, 72.        , 72.        ,
       72.        , 71.63157895, 71.33333333, 71.3271028 , 71.27393939])

In [61]:
px.bar(top_10_overall, x = top_10_overall.index, y= top_10_overall.values, labels= {'nationality' : 'Nationality', 'y' : 'Average Overall'})

In [62]:
df.columns

Index(['id', 'name', 'age', 'nationality', 'overall', 'potential', 'club',
       'value', 'wage', 'preferred_foot', 'international_reputation',
       'skill_moves', 'position', 'joined', 'contract_valid_until', 'height',
       'weight', 'release_clause'],
      dtype='object')

### Another way to plot the same Chart

In [63]:
top_10_overall = df.groupby('nationality')['overall'].mean().sort_values(ascending= False).head(10).reset_index()
top_10_overall

            nationality    overall
0  United Arab Emirates  77.000000
1  Central African Rep.  73.333333
2                Israel  72.142857
3                  Oman  72.000000
4   São Tomé & Príncipe  72.000000
5    Dominican Republic  72.000000
6            Cape Verde  71.631579
7                  Togo  71.333333
8              Portugal  71.327103
9                Brazil  71.273939

In [64]:
px.bar(top_10_overall, x = 'nationality', y= 'overall', title= 'Top 10 Countries per Overall',
                                                        labels= {'nationality' : 'Nationality', 'overall' : 'Average Overall'})

### **What are the top 10 clubs with highest number of playes ?**

In [65]:
top_10_clubs = df.groupby('club')['id'].count().sort_values(ascending= False).head(10).reset_index()
top_10_clubs

                  club  id
0            Liverpool  33
1             RC Celta  33
2          Real Madrid  33
3  TSG 1899 Hoffenheim  33
4       Rayo Vallecano  33
5          Valencia CF  33
6              Chelsea  33
7     Newcastle United  33
8      Manchester City  33
9  Eintracht Frankfurt  33

In [66]:
px.bar(top_10_clubs, x = 'club', y= 'id', title= 'Top 10 Countries per number of players', labels= {'club' : 'Club', 'id' : 'Count'})

### **what are the Top 20 clubs with highest player Value ?**

In [68]:
top_club_value = df.groupby('club')['value'].sum().sort_values(ascending= False).reset_index().head(20)
top_club_value

                   club     value
0           Real Madrid  874425.0
1          FC Barcelona  852600.0
2       Manchester City  786555.0
3              Juventus  704475.0
4     FC Bayern München  679025.0
5       Atlético Madrid  644525.0
6   Paris Saint-Germain  625325.0
7     Tottenham Hotspur  618450.0
8               Chelsea  606815.0
9     Manchester United  588850.0
10            Liverpool  585055.0
11               Napoli  514000.0
12                Inter  466485.0
13              Arsenal  435990.0
14    Borussia Dortmund  420245.0
15                Milan  417000.0
16          Valencia CF  394225.0
17                Lazio  352135.0
18             FC Porto  335600.0
19                 Roma  335450.0

In [69]:
px.bar(top_club_value, x= 'club', y= 'value', title= 'Top 10 Clubs with Highest Player Values',
                                                        labels= {'club' : 'Club', 'value' : 'Total Player Value'})

### **What is the average height per position ?**

In [70]:
avg_position_height = df.groupby('position')['height'].mean().sort_values(ascending= False).reset_index()
avg_position_height

   position      height
0        GK  188.206094
1       RCB  186.538067
2       LCB  186.221476
3        CB  186.142611
4        ST  182.333840
5        LS  182.263495
6        RS  181.843781
7       CDM  180.510962
8       RDM  180.412276
9       LDM  179.883013
10      RCM  179.276744
11      LCM  178.994910
12       CM  178.897531
13      LWB  178.842051
14      RWB  178.821839
15       RB  178.629306
16       LB  178.611632
17       CF  177.456757
18       LW  177.032567
19       RM  176.924452
20       LM  176.635249
21      CAM  176.618418
22       RF  176.530000
23      LAM  176.469524
24       RW  176.310795
25      RAM  175.864762
26       LF  173.058667

In [71]:
px.bar(avg_position_height, x= 'position', y= 'height', title= 'Average height per position',
                                                        labels= {'position' : 'Position', 'height' : 'Average Height'})

### **What is the average weight per position ?**

In [72]:
avg_position_weight = df.groupby('position')['weight'].mean().sort_values(ascending= False).reset_index()
avg_position_weight

   position     weight
0        GK  81.961479
1       LCB  80.505103
2       RCB  80.388747
3        CB  79.247229
4        LS  77.271379
5        RS  77.090330
6        ST  76.599763
7       RDM  75.358964
8       CDM  74.466140
9       LDM  73.895641
10      LWB  73.510980
11      RWB  73.424553
12      RCM  73.299061
13      LCM  73.074954
14       LB  72.920215
15       RB  72.827987
16      LAM  72.617919
17       RF  72.603070
18       CM  72.387288
19       CF  71.986276
20       LM  71.264482
21       RM  70.992034
22       LW  70.978658
23      CAM  70.784754
24       RW  70.464585
25       LF  70.276521
26      RAM  69.464375

In [73]:
px.bar(avg_position_weight, x= 'position', y= 'weight', title= 'Average Weight per position',
                                                        labels= {'position' : 'Position', 'weight' : 'Average Weight'})

### How does player values increase over the years ?

In [75]:
# First sort dataframe based on joined column
df.sort_values(by= 'joined', ignore_index= True)

,id,name,age,nationality,overall,potential,club,value,wage,preferred_foot,international_reputation,skill_moves,position,joined,contract_valid_until,height,weight,release_clause
0,140029,O. Pérez,45,Mexico,71,71,Pachuca,160.0,8.0,Right,2.0,1.0,GK,1991,2021-01-01,172.72,74.842680,272.0
1,140181,H. Sogahata,38,Japan,68,68,Kashima Antlers,60.0,3.0,Right,1.0,1.0,GK,1998,2021-01-01,187.96,79.832192,78.0
2,140180,M. Ogasawara,39,Japan,65,65,Kashima Antlers,40.0,2.0,Right,2.0,2.0,CDM,1998,2021-01-01,172.72,72.121128,52.0
3,168879,M. Al Shalhoub,37,Saudi Arabia,66,66,Al Hilal,220.0,8.0,Left,1.0,3.0,CAM,1998,2019-01-01,162.56,66.224432,374.0
4,140183,S. Narazaki,42,Japan,65,65,Nagoya Grampus,40.0,1.0,Right,2.0,1.0,GK,1999,2021-01-01,187.96,79.832192,50.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17913,244025,D. Osei Yaw,19,France,64,75,Toulouse Football Club,750.0,3.0,Right,1.0,3.0,RW,2018,2019-01-01,182.88,72.121128,1700.0
17914,236007,E. Barco,19,Argentina,73,88,Atlanta United,8500.0,4.0,Right,1.0,3.0,LM,2018,2021-01-01,167.64,66.224432,18100.0
17915,204776,T. Leistner,27,Germany,73,74,Queens Park Rangers,3800.0,9.0,Right,1.0,2.0,RCB,2018,2021-01-01,190.50,89.811216,7500.0
17916,219448,M. Heinloth,26,Germany,64,66,Zagłębie Sosnowiec,450.0,1.0,Right,1.0,2.0,RB,2018,2019-01-01,177.80,74.842680,641.0
17917,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,177.80,79.832192,165.0

#### What is the distribution of wages for each position ?

In [76]:
px.box(df, x= 'position', y= 'wage')

In [77]:
df[['value', 'release_clause']].corr()

                   value  release_clause
value           1.000000        0.973462
release_clause  0.973462        1.000000

###  Does Player value affect release clause ?

In [78]:
px.scatter(df, x= 'value', y= 'release_clause')

### Does Skills affect Overall player performance ?

In [79]:
px.scatter(df, x= 'overall', y= 'skill_moves')

In [80]:
df[['overall', 'skill_moves']].corr()

              overall  skill_moves
overall      1.000000     0.415865
skill_moves  0.415865     1.000000

### Does Age affect overall player performance ?

In [81]:
px.scatter(df, x= 'age', y= 'overall')

In [82]:
df[['overall', 'age']].corr()

          overall       age
overall  1.000000  0.453252
age      0.453252  1.000000

### Does players with preferred right foot have higher Values than players with left preferred foot ?

In [83]:
px.box(df, x= 'preferred_foot', y= 'value')

### Create another dataframe without extreme outliers values

In [84]:
# ! pip install datasist

In [88]:
from datasist.structdata import detect_outliers
outlier_indices = detect_outliers(df, 0, ['value', 'wage', 'release_clause'])

print(outlier_indices)
len(outlier_indices)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 537, 538, 539, 541, 543, 544, 546, 548, 549, 550, 551, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 717, 718, 720, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859, 861, 862, 863, 864, 865, 866, 868, 869, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896, 897, 898, 899, 901, 902, 903, 904, 907, 909, 910, 911, 912, 913, 914, 915, 916, 917, 919, 920, 922, 923, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 941, 942, 943, 944, 945, 947, 949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961, 962, 963, 964, 965, 966, 968, 969, 970, 971, 972, 973, 974, 975, 976, 977, 978, 979, 980, 981, 983, 985, 987, 989, 990, 992, 993, 994, 995, 996, 997, 999, 1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1013, 1014, 1015, 1016, 1017, 1018, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044, 1045, 1046, 1047, 1049, 1050, 1051, 1052, 1053, 1054, 1055, 1056, 1057, 1058, 1059, 1060, 1061, 1062, 1064, 1065, 1066, 1067, 1068, 1069, 1071, 1072, 1073, 1074, 1075, 1077, 1078, 1080, 1081, 1083, 1085, 1086, 1087, 1088, 1089, 1090, 1091, 1093, 1094, 1095, 1096, 1097, 1098, 1099, 1100, 1101, 1102, 1103, 1104, 1105, 1106, 1107, 1108, 1110, 1111, 1112, 1113, 1114, 1115, 1116, 1117, 1118, 1119, 1120, 1121, 1122, 1123, 1124, 1125, 1126, 1127, 1129, 1130, 1131, 1132, 1133, 1134, 1135, 1136, 1137, 1139, 1140, 1141, 1142, 1143, 1144, 1145, 1146, 1147, 1148, 1149, 1150, 1151, 1152, 1153, 1154, 1155, 1156, 1157, 1158, 1159, 1161, 1162, 1163, 1164, 1165, 1166, 1167, 1168, 1169, 1170, 1171, 1172, 1173, 1174, 1175, 1176, 1177, 1178, 1179, 1180, 1181, 1182, 1183, 1184, 1185, 1186, 1187, 1188, 1189, 1191, 1192, 1193, 1194, 1195, 1196, 1197, 1198, 1199, 1200, 1201, 1202, 1204, 1205, 1206, 1207, 1208, 1209, 1211, 1213, 1214, 1215, 1216, 1217, 1218, 1219, 1220, 1221, 1222, 1223, 1224, 1225, 1226, 1227, 1228, 1229, 1230, 1231, 1232, 1233, 1234, 1235, 1236, 1237, 1238, 1239, 1240, 1241, 1242, 1243, 1244, 1245, 1246, 1247, 1248, 1249, 1250, 1251, 1252, 1253, 1254, 1255, 1256, 1257, 1258, 1259, 1260, 1262, 1264, 1265, 1266, 1267, 1268, 1269, 1270, 1271, 1272, 1274, 1275, 1276, 1278, 1279, 1280, 1281, 1282, 1283, 1285, 1286, 1287, 1288, 1289, 1290, 1291, 1293, 1294, 1295, 1296, 1297, 1298, 1299, 1300, 1301, 1302, 1303, 1304, 1305, 1306, 1309, 1310, 1311, 1312, 1313, 1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321, 1323, 1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332, 1333, 1334, 1335, 1336, 1337, 1338, 1339, 1341, 1342, 1344, 1345, 1346, 1347, 1348, 1350, 1351, 1352, 1353, 1354, 1355, 1356, 1357, 1358, 1359, 1360, 1361, 1362, 1364, 1365, 1366, 1367, 1368, 1369, 1370, 1371, 1373, 1374, 1375, 1377, 1378, 1379, 1380, 1381, 1382, 1383, 1384, 1385, 1386, 1387, 1388, 1389, 1390, 1391, 1392, 1393, 1394, 1395, 1396, 1397, 1398, 1399, 1400, 1401, 1402, 1403, 1404, 1405, 1406, 1407, 1409, 1410, 1411, 1412, 1413, 1414, 1415, 1416, 1417, 1418, 1419, 1420, 1421, 1422, 1423, 1427, 1428, 1429, 1430, 1431, 1433, 1434, 1435, 1436, 1437, 1438, 1439, 1440, 1441, 1442, 1443, 1444, 1445, 1446, 1447, 1448, 1449, 1450, 1451, 1452, 1454, 1455, 1456, 1457, 1458, 1459, 1460, 1461, 1462, 1463, 1464, 1465, 1466, 1467, 1468, 1469, 1470, 1471, 1472, 1473, 1475, 1476, 1477, 1478, 1479, 1480, 1481, 1482, 1483, 1484, 1485, 1486, 1487, 1488, 1489, 1490, 1491, 1492, 1493, 1494, 1495, 1496, 1497, 1498, 1499, 1500, 1501, 1502, 1503, 1504, 1506, 1507, 1508, 1509, 1510, 1511, 1512, 1513, 1516, 1517, 1519, 1520, 1522, 1523, 1524, 1526, 1527, 1528, 1529, 1530, 1531, 1532, 1533, 1534, 1536, 1537, 1538, 1539, 1540, 1541, 1542, 1543, 1544, 1545, 1546, 1547, 1548, 1549, 1550, 1551, 1553, 1554, 1555, 1556, 1557, 1559, 1561, 1562, 1563, 1564, 1565, 1566, 1567, 1568, 1569, 1570, 1571, 1572, 1573, 1574, 1575, 1576, 1578, 1579, 1580, 1581, 1582, 1583, 1584, 1586, 1588, 1589, 1590, 1591, 1592, 1593, 1594, 1597, 1598, 1599, 1600, 1602, 1603, 1604, 1605, 1606, 1607, 1608, 1609, 1610, 1612, 1614, 1615, 1616, 1617, 1618, 1619, 1620, 1621, 1622, 1624, 1627, 1628, 1630, 1631, 1632, 1633, 1634, 1635, 1636, 1637, 1638, 1639, 1640, 1642, 1643, 1644, 1645, 1646, 1647, 1648, 1650, 1651, 1652, 1653, 1655, 1657, 1658, 1659, 1660, 1662, 1663, 1665, 1666, 1667, 1668, 1669, 1670, 1672, 1674, 1676, 1678, 1681, 1682, 1683, 1684, 1685, 1686, 1687, 1688, 1689, 1690, 1692, 1693, 1694, 1695, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704, 1705, 1706, 1708, 1709, 1710, 1711, 1712, 1713, 1714, 1715, 1717, 1720, 1721, 1722, 1725, 1726, 1727, 1728, 1729, 1730, 1731, 1732, 1733, 1734, 1735, 1736, 1737, 1738, 1739, 1740, 1741, 1742, 1744, 1745, 1746, 1747, 1748, 1749, 1750, 1751, 1752, 1754, 1755, 1756, 1757, 1760, 1761, 1762, 1763, 1764, 1765, 1766, 1768, 1769, 1770, 1773, 1774, 1777, 1778, 1780, 1781, 1782, 1783, 1784, 1785, 1786, 1787, 1788, 1789, 1790, 1791, 1792, 1793, 1794, 1795, 1796, 1798, 1799, 1801, 1802, 1803, 1804, 1805, 1806, 1808, 1809, 1810, 1811, 1812, 1813, 1814, 1815, 1816, 1817, 1818, 1819, 1820, 1821, 1822, 1823, 1824, 1825, 1826, 1828, 1829, 1831, 1833, 1836, 1837, 1838, 1839, 1841, 1842, 1843, 1844, 1845, 1846, 1847, 1848, 1850, 1851, 1852, 1854, 1855, 1857, 1858, 1859, 1860, 1861, 1862, 1863, 1864, 1865, 1866, 1867, 1868, 1869, 1870, 1871, 1872, 1873, 1874, 1875, 1877, 1878, 1879, 1880, 1881, 1882, 1883, 1884, 1885, 1886, 1887, 1888, 1889, 1891, 1893, 1894, 1895, 1896, 1897, 1898, 1899, 1900, 1901, 1902, 1904, 1905, 1906, 1908, 1909, 1910, 1911, 1912, 1913, 1915, 1916, 1917, 1919, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1935, 1936, 1937, 1938, 1940, 1943, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1959, 1961, 1963, 1964, 1965, 1966, 1967, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1990, 1991, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2002, 2004, 2005, 2006, 2008, 2009, 2010, 2011, 2012, 2014, 2015, 2017, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030, 2031, 2032, 2033, 2034, 2035, 2036, 2037, 2038, 2039, 2040, 2041, 2042, 2044, 2045, 2046, 2047, 2049, 2050, 2051, 2054, 2055, 2058, 2059, 2061, 2062, 2063, 2065, 2068, 2069, 2070, 2072, 2073, 2075, 2077, 2079, 2080, 2081, 2082, 2084, 2085, 2086, 2087, 2088, 2089, 2090, 2092, 2093, 2094, 2096, 2097, 2098, 2099, 2100, 2101, 2102, 2103, 2106, 2108, 2109, 2112, 2113, 2114, 2115, 2116, 2118, 2119, 2121, 2123, 2124, 2125, 2126, 2127, 2128, 2129, 2132, 2135, 2136, 2137, 2138, 2141, 2142, 2143, 2144, 2145, 2147, 2148, 2150, 2151, 2153, 2158, 2159, 2160, 2161, 2164, 2166, 2168, 2169, 2170, 2171, 2172, 2173, 2175, 2176, 2178, 2180, 2181, 2182, 2185, 2186, 2188, 2189, 2190, 2191, 2192, 2193, 2195, 2196, 2197, 2199, 2200, 2201, 2204, 2207, 2208, 2209, 2211, 2212, 2214, 2215, 2218, 2219, 2223, 2224, 2226, 2227, 2229, 2230, 2231, 2232, 2233, 2238, 2239, 2240, 2243, 2245, 2246, 2247, 2248, 2249, 2252, 2253, 2255, 2256, 2257, 2258, 2259, 2260, 2261, 2262, 2263, 2264, 2266, 2267, 2268, 2270, 2271, 2273, 2275, 2276, 2277, 2278, 2280, 2281, 2285, 2287, 2290, 2293, 2294, 2295, 2296, 2297, 2298, 2299, 2301, 2302, 2303, 2304, 2305, 2309, 2310, 2311, 2312, 2313, 2316, 2317, 2318, 2319, 2320, 2323, 2324, 2325, 2327, 2328, 2330, 2331, 2333, 2335, 2336, 2337, 2339, 2340, 2341, 2342, 2343, 2344, 2345, 2346, 2347, 2348, 2349, 2350, 2352, 2353, 2355, 2356, 2358, 2359, 2362, 2363, 2364, 2365, 2366, 2367, 2368, 2369, 2370, 2371, 2373, 2375, 2378, 2379, 2380, 2381, 2382, 2383, 2384, 2385, 2386, 2387, 2388, 2390, 2391, 2393, 2395, 2397, 2398, 2400, 2401, 2402, 2403, 2404, 2405, 2411, 2412, 2413, 2415, 2416, 2418, 2419, 2420, 2422, 2424, 2426, 2427, 2428, 2429, 2432, 2434, 2435, 2436, 2437, 2438, 2440, 2441, 2443, 2445, 2446, 2447, 2449, 2450, 2451, 2452, 2453, 2454, 2455, 2456, 2457, 2459, 2460, 2463, 2464, 2465, 2466, 2468, 2469, 2470, 2471, 2472, 2474, 2475, 2476, 2478, 2480, 2483, 2484, 2486, 2487, 2488, 2490, 2491, 2494, 2496, 2498, 2499, 2500, 2501, 2502, 2503, 2504, 2505, 2506, 2508, 2509, 2511, 2514, 2516, 2517, 2518, 2519, 2520, 2521, 2522, 2526, 2527, 2529, 2532, 2533, 2538, 2539, 2540, 2542, 2544, 2550, 2551, 2552, 2553, 2554, 2555, 2556, 2557, 2560, 2561, 2562, 2566, 2568, 2569, 2570, 2571, 2572, 2573, 2577, 2579, 2581, 2592, 2595, 2601, 2603, 2604, 2608, 2609, 2610, 2627, 2629, 2631, 2645, 2649, 2657, 2658, 2665, 2666, 2667, 2678, 2681, 2683, 2687, 2690, 2697, 2698, 2701, 2705, 2706, 2707, 2708, 2712, 2714, 2717, 2718, 2719, 2720, 2734, 2738, 2745, 2749, 2754, 2762, 2764, 2771, 2775, 2784, 2785, 2790, 2791, 2793, 2794, 2796, 2801, 2807, 2809, 2811, 2828, 2832, 2837, 2838, 2848, 2855, 2857, 2859, 2861, 2864, 2865, 2866, 2871, 2872, 2876, 2881, 2884, 2887, 2890, 2892, 2893, 2894, 2895, 2898, 2899, 2906, 2915, 2917, 2921, 2922, 2926, 2927, 2934, 2935, 2936, 2946, 2947, 2951, 2952, 2954, 2957, 2959, 2963, 2965, 2968, 2975, 2978, 2981, 2991, 2996, 2998, 3000, 3001, 3014, 3022, 3023, 3024, 3025, 3028, 3034, 3036, 3037, 3039, 3045, 3050, 3052, 3056, 3065, 3070, 3071, 3073, 3074, 3075, 3076, 3087, 3088, 3096, 3103, 3105, 3107, 3112, 3115, 3116, 3122, 3124, 3125, 3128, 3129, 3130, 3133, 3134, 3136, 3137, 3139, 3146, 3152, 3159, 3165, 3202, 3207, 3236, 3237, 3290, 3293, 3328, 3342, 3354, 3365, 3372, 3399, 3433, 3440, 3480, 3496, 3521, 3570, 3623, 3624, 3633, 3641, 3671, 3714, 3723, 3727, 3739, 3769, 3793, 3803, 3815, 3838, 3844, 3868, 3883, 4192, 4202, 41, 152, 317, 420, 536, 547, 565, 716, 719, 721, 867, 870, 883, 900, 905, 906, 918, 921, 924, 940, 982, 988, 991, 998, 1012, 1019, 1048, 1070, 1079, 1084, 1109, 1138, 1160, 1210, 1212, 1261, 1273, 1277, 1322, 1324, 1363, 1372, 1376, 1424, 1453, 1474, 1514, 1525, 1558, 1585, 1625, 1649, 1654, 1671, 1677, 1680, 1696, 1716, 1718, 1719, 1723, 1743, 1759, 1767, 1779, 1807, 1830, 1832, 1835, 1840, 1849, 1856, 1890, 1892, 1914, 1941, 1944, 1958, 1960, 1992, 2000, 2016, 2074, 2076, 2110, 2117, 2131, 2140, 2146, 2155, 2165, 2174, 2184, 2213, 2217, 2234, 2242, 2250, 2254, 2269, 2279, 2283, 2288, 2300, 2308, 2314, 2321, 2334, 2354, 2360, 2361, 2372, 2394, 2408, 2409, 2430, 2439, 2473, 2492, 2493, 2495, 2530, 2541, 2558, 2565, 2567, 2575, 2582, 2584, 2590, 2593, 2602, 2614, 2615, 2620, 2626, 2628, 2637, 2644, 2650, 2655, 2664, 2668, 2669, 2670, 2673, 2674, 2675, 2676, 2679, 2684, 2685, 2689, 2695, 2699, 2700, 2702, 2704, 2721, 2726, 2730, 2732, 2748, 2756, 2758, 2765, 2773, 2778, 2789, 2797, 2798, 2815, 2817, 2818, 2824, 2825, 2830, 2839, 2840, 2841, 2847, 2851, 2853, 2870, 2874, 2879, 2882, 2886, 2888, 2891, 2896, 2900, 2910, 2924, 2928, 2931, 2941, 2943, 2949, 2960, 2973, 2974, 2987, 2993, 3009, 3012, 3013, 3027, 3029, 3035, 3040, 3041, 3042, 3072, 3077, 3082, 3090, 3092, 3100, 3113, 3131, 3142, 3153, 3166, 3168, 3179, 3181, 3182, 3190, 3194, 3197, 3204, 3213, 3224, 3228, 3231, 3235, 3255, 3260, 3261, 3265, 3271, 3273, 3284, 3298, 3300, 3303, 3326, 3334, 3338, 3344, 3346, 3359, 3375, 3378, 3381, 3382, 3384, 3388, 3389, 3392, 3393, 3405, 3411, 3415, 3419, 3421, 3427, 3435, 3438, 3443, 3444, 3454, 3460, 3464, 3465, 3472, 3473, 3481, 3492, 3510, 3519, 3532, 3536, 3543, 3544, 3550, 3553, 3564, 3581, 3598, 3612, 3617, 3621, 3627, 3628, 3638, 3649, 3650, 3661, 3670, 3681, 3685, 3693, 3697, 3700, 3712, 3718, 3726, 3731, 3734, 3743, 3747, 3752, 3759, 3799, 3800, 3805, 3808, 3809, 3816, 3817, 3824, 3825, 3850, 3854, 3857, 3860, 3862, 3863, 3875, 3882, 3886, 3891, 3894, 3902, 3914, 3916, 3921, 3925, 3932, 3937, 3940, 3947, 3968, 3971, 3980, 3995, 4004, 4019, 4021, 4023, 4035, 4043, 4060, 4067, 4073, 4093, 4155, 4173, 4188, 4189, 4191, 4196, 4219, 4227, 4250, 4267, 4273, 4306, 4308, 4314, 4337, 4343, 4349, 4361, 4373, 4374, 4376, 4381, 4399, 4401, 4409, 4414, 4429, 4432, 4439, 4447, 4448, 4452, 4463, 4466, 4487, 4491, 4531, 4587, 4593, 4597, 4611, 4619, 4628, 4638, 4641, 4649, 4652, 4663, 4687, 4696, 4727, 4781, 4851, 4863, 4883, 4901, 4909, 4912, 4923, 4947, 4959, 5031, 5039, 5046, 5060, 5064, 5079, 5106, 5127, 5184, 5185, 5193, 5203, 5212, 5241, 5291, 5296, 5306, 5332, 5343, 5351, 5356, 5384, 5387, 5427, 5446, 5448, 5458, 5468, 5473, 5474, 5500, 5536, 5545, 5565, 5577, 5592, 5595, 5610, 5612, 5631, 5709, 5764, 5780, 5847, 5894, 5971, 6002, 6016, 6022, 6036, 6085, 6097, 6118, 6150, 6158, 6160, 6216, 6331, 6354, 6384, 6392, 6452, 6612, 6636, 6686, 6765, 6805, 6948, 7117, 7298, 7422, 7513, 7606, 8114, 8277, 8588, 8992, 10016, 2728, 3301, 4211, 4589]

2921

In [89]:
df_wo_outliers = df.drop(outlier_indices)
df_wo_outliers

,id,name,age,nationality,overall,potential,club,value,wage,preferred_foot,international_reputation,skill_moves,position,joined,contract_valid_until,height,weight,release_clause
318,5479,Casillas,37,Spain,82,82,FC Porto,1500.0,10.0,Left,4.0,1.0,GK,2015,2019-01-01,185.42,83.914520,3000.0
540,147782,I. Denisov,34,Russia,80,80,Lokomotiv Moscow,4500.0,1.0,Right,2.0,3.0,RDM,2013,2019-01-01,175.26,69.853168,9400.0
542,146748,Diego López,36,Spain,80,80,RCD Espanyol,2000.0,17.0,Right,3.0,1.0,GK,2017,2020-01-01,195.58,88.904032,4200.0
545,142754,J. Mascherano,34,Argentina,80,80,Hebei China Fortune FC,4500.0,20.0,Right,4.0,2.0,LDM,2018,2019-01-01,175.26,73.028312,9700.0
552,49031,S. Sorrentino,39,Italy,80,80,Chievo Verona,1000.0,10.0,Right,2.0,1.0,GK,2016,2022-01-01,185.42,84.821704,1700.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17913,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,175.26,60.781328,143.0
17914,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,190.50,77.110640,113.0
17915,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,172.72,67.131616,165.0
17916,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,177.80,69.853168,143.0
17917,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,177.80,79.832192,165.0

In [90]:
px.box(df_wo_outliers, x= 'position', y= 'wage')

In [91]:
px.histogram(df_wo_outliers.wage)